### ISSUE TITLE
Decibels for Band Frequencies

### ISSUE THREAD

**Issue by iDevelopper** [tumtumtum/StreamingKit#337] opened 2017-04-28 10:54 UTC
Hi,

How can I retrieve decibels values for band frequencies while streaming?

I would like to show an EQ histogram with these values.

Thanks

**Comment by doriansgithub** [comment] 2017-05-05 00:21
Do you know if this is what we need for the eq to work? 

[audioPlayer appendFrameFilterWithName:@"MyCustomFilter" block:^(UInt32 channelsPerFrame, UInt32 bytesPerFrame, UInt32 frameCount, void* frames)
{
   ...
}];

Thanks!

**Comment by iDevelopper** [comment] 2017-05-05 00:48
Do you mean visualization? Or setGain for band? I got it for visualization with the additions of FreeStreamer.

**Comment by doriansgithub** [comment] 2017-05-05 00:49
Hey, thanks for responding!

No, we got visualization working with an iPodVisualizer.  We need it to EQ the Audio.

**Comment by tumtumtum** [comment] 2017-05-05 07:09
You can use the frame filter to calculate the decibels per band frequency from the raw PCM audio data. You will have to do the FFT and decimals calculation yourself if you want to render a visualisation.

To configure the EQ (control levels in different frequency band):

- Set ```STKAudioPlayer.equalizerEnabled``` to YES.
-  Fill ```STKAudioPlayerOptions.equalizerBandFrequencies``` with frequency values for each band you want to control (measured in Hz) and then zero terminate the array.  For example: 200, 4000, 8000, 16000, 32000, 0. These bands can only be configured when creating a new ```STKAudioPlayer```.
- Set the gain for each band using ```STKAudioplayer.setGain:forEqualizerBand ```. Values range from a low of -96 to a high of +24. You can change these values during playback.

**Comment by iDevelopper** [comment] 2017-05-05 07:17
@tumtumtum , thanks.

It would be nice to have this functionality integrated in this great library as I think you already know how to do this 👍

**Comment by doriansgithub** [comment] 2017-05-05 15:38
Hi Tum, thanks for responding!  We have done exactly that, and when we move the slider, the audio just dies.  So the interruption is not the key?  

#import "StreamingPlayer.h"
#import "QueueID.h"

@implementation StreamingPlayer

- (instancetype)init {
    self = [super initWithOptions:(STKAudioPlayerOptions) {
        .flushQueueOnSeek = YES,
        .enableVolumeMixer = NO,
        .readBufferSize = 0,
        .bufferSizeInSeconds = 0,
        .secondsRequiredToStartPlaying = 0,
        .gracePeriodAfterSeekInSeconds = 0,
        .secondsRequiredToStartPlayingAfterBufferUnderun = 0,
        .equalizerBandFrequencies = 
            32.0, 42.0, 52.0, 64.0, 74.0,14000.0, 16000.0
        }
    }];
    if (self) {
        self.delegate = self;
    }
    return self;
}

-(void)setBandValue:(Float32)gainValue forEqualizerBand:(int)bandIndex {
    [self setGain:gainValue forEqualizerBand:bandIndex];
}

And on the EQ ViewController, we have this for each slider:

#pragma mark HIGH Gain Levels
- (Float32 )convertEQToEQNumbers:(NSInteger )selectedEQLevel {
    // - 96
    // + 24
    if (selectedEQLevel == 0) {
        return 0.0;
    } else if (selectedEQLevel > 0) {
        return (24.0 / 10.0) * selectedEQLevel;
    } else if (0 > selectedEQLevel) {
        return (96.0 / 10.0) * selectedEQLevel;
    }
    return 0.0;
}
- (IBAction)dedicatedHighGainValue1:(UISlider *)sender {
    selectedEQHStateLevelInt1 = sender.value;
    [UniversallyPlayer.defaultPlayer setBandValue:[self convertEQToEQNumbers: selectedEQHStateLevelInt1]  forEqualizerBand:EqualizerBand_TrebbleLB_2000];

**Comment by doriansgithub** [comment] 2017-05-05 15:40
Oh, I missed the ZERO termination.  I'm trying that right now!  Thanks!

**Comment by iDevelopper** [comment] 2017-05-05 15:49
Do you have the histogram visualization (graphic equalizer)?

**Comment by doriansgithub** [comment] 2017-05-05 15:53
I don't, our EQ won't have that type of visuals.

**Comment by iDevelopper** [comment] 2017-05-05 15:59
Ok then your visual does not represent the real visualization after setGain. the visual represent the incoming buffer, right?

**Comment by doriansgithub** [comment] 2017-05-05 16:23
Our visualizer is tied to the average Power in Decibels.  It is very fast, but it's a particle generator, not a line, which might be what you are talking about.

- (void)update {
    emitterLayer.emitterSize=CGSizeMake(emitterLayer.emitterSize.width, [AppDelegate SharedDelegate].height);
    float scale = 0.5;
    if (_avPlayer.state == STKAudioPlayerStatePlaying )
    {
        float power = 0.0f;
        for (int i = 0; i < _avPlayer.frameFilters.count; i++) {
            power += [_avPlayer averagePowerInDecibelsForChannel:i];
        }
        power /= _avPlayer.frameFilters.count;
        float level = meterTable.ValueAt(power);
        scale = level * 5;
    }
    [emitterLayer setValue:@(scale) forKeyPath:@"emitterCells.cell.emitterCells.childCell.scale"];
}

**Comment by doriansgithub** [comment] 2017-05-05 16:31
Hi Tam, adding the zero at the end of the bands didn't help.  We must be creating the new STKAudioPlayer wrong.  Where should be set the new player?  Do you have a sample of a working EQ?  Maybe you should include a single band in your sample app?

**Comment by doriansgithub** [comment] 2017-05-07 01:22
Hi Tam, if we create a new instance of the player, wouldn't that interrupt the stream and cause the audio to break?

**Comment by iDevelopper** [comment] 2017-05-07 14:52
No

**Comment by doriansgithub** [comment] 2017-05-07 22:37
Dude, we've tried everything, half of the sliders don't do anything, and the other sliders cause the sound to just die.   We are going KooKoo!

**Comment by iDevelopper** [comment] 2017-05-08 11:42
I don't understand, for me it works. I have 11 bands. I have 11 sliders, and I call setGain:ForEqualizerBand: when a slider value change.

**Comment by doriansgithub** [comment] 2017-05-09 15:01
How are you creating the new stkaudioplayer?  Do you see anything wrong in my code snippet?  And how are you giving value to the sliders?  Are you implementing the -96 +24 like we are? Or just assigning the slider value directly?

**Comment by iDevelopper** [comment] 2017-05-09 15:45
I create a new audio player after each pause or interruptions as I play some url live streaming, not file url:

```
- (void)newAudioPlayer {
    if (_audioPlayer) {
        [_audioPlayer stop];
        _audioPlayer = nil;
    }
    
    self.audioPlayer = [[STKAudioPlayer alloc] initWithOptions:(STKAudioPlayerOptions){ .flushQueueOnSeek = NO, .enableVolumeMixer = YES, .equalizerBandFrequencies = {20, 40, 80, 160, 320, 640, 1280, 2560, 5120, 10240, 20480, 0} }];
    _appDelegate.playViewController = self;
    _audioPlayer.delegate = self;
    _audioPlayer.meteringEnabled = YES;
    _audioPlayer.equalizerEnabled = YES;
    _audioPlayer.volume = 1;
    
    for (int i = 0; i < _gains.count; i++) {
        [_audioPlayer setGain:[_gains[i]floatValue] forEqualizerBand:i];
    }
    
    [_audioPlayer appendFrameFilterWithName:@"CustomEQFilter" block:^(UInt32 channelsPerFrame, UInt32 bytesPerFrame, UInt32 frameCount, void* frames)
     {
         UInt32* samples32 = (UInt32*)frames;
         
         AudioStreamPacketDescription description;
         description.mDataByteSize = bytesPerFrame * frameCount;
         description.mStartOffset = 0;
         description.mVariableFramesInPacket = 0;
         
         [_frequencyAnalyzer audioPlayer:_audioPlayer samplesAvailable:samples32 description:description];
     }];
}
```

_frequencyAnalyser is a class of FreeStreamer I have integred in my project.

https://github.com/muhku/FreeStreamer

I modified a little the additions in this project (the delegate method and FSFrequencyPlotView class for display an histogram.

In my EQViewController, for setting gain for bands I have 11 sliders:

![img_2443 - copie](https://cloud.githubusercontent.com/assets/1782450/25859434/d1e9c2d0-34de-11e7-9b03-812374bf3090.png)

I set the gain like this:

```
- (void)sliderChanged:(UISlider *)slider {
    [_audioPlayer setGain:slider.value forEqualizerBand:(int)slider.tag - 10];

    _frequencyAnalyzer.gains[slider.tag - 10] = [NSNumber numberWithFloat:slider.value];
    
    UIButton *button = [self.view viewWithTag:100 + slider.tag - 10];
    [button setTitle:[NSString stringWithFormat:@"%.2f",[_frequencyAnalyzer.gains[slider.tag - 10]floatValue]] forState:UIControlStateNormal];
}
```

**Comment by doriansgithub** [comment] 2017-05-09 16:21
Bro, thanks a Gazillion for this.  If we can't get this to work with this, we'll retire to the darkest cave we can find.

**Comment by doriansgithub** [comment] 2017-05-09 18:30
But this frequencyAnalizer is not required, correct?  You are using this to get your histogram, right?  I also don't see the file in the FreeStreamer.

**Comment by iDevelopper** [comment] 2017-05-09 19:49
https://github.com/muhku/FreeStreamer/tree/master/Additions

**Comment by doriansgithub** [comment] 2017-05-10 01:11
I'm I reading this right?

    /// The size of the decompressed buffer (Default is 10 seconds which uses about 1.7MB of RAM)
    Float32 bufferSizeInSeconds;
    /// Number of seconds of decompressed audio is required before playback first starts for each item (Default is 0.5 seconds. Must be larger than bufferSizeInSeconds)
    Float32 secondsRequiredToStartPlaying;

If the default for the bufferSizeInSeconds is 10 seconds, and the size of the secondsRequiredToStartPlaying is .05 seconds, how can the aft be greater than the afore?

**Comment by iDevelopper** [comment] 2017-05-10 04:20
I don't know, not tested. I only use StreamingKit to play live stream url, not file url.

**Comment by doriansgithub** [comment] 2017-05-10 04:27
I think I'm going to try Novocaine.  Just can't get this library to work right.  Thanks for all your help! Really appreciate it.

**Comment by tumtumtum** [comment] 2017-05-10 10:23
SecondsRequiredToStartPlaying allows the player to start playing immediately even if the buffer isn't yet full....if the connection speed is faster than the bitrate then the b

**Comment by doriansgithub** [comment] 2017-05-10 15:56
Thanks for answering!  I had lost hope.

We are playing from the local iTunes library.  I've tried this:

    QueueID* queueId = (QueueID*)queueItemId;
    MPMediaItem *item =
    [MediaPlayerNavigation nextSongFromArray:UniversallyPlayer.defaultPlayer.arrSongs
                                     isQueue:YES];
    [MediaPlayerNavigation fillSongInfo:item];
    NSURL *url = [item valueForProperty:MPMediaItemPropertyAssetURL];
    [self queueDataSource:[STKAudioPlayer dataSourceFromURL:url]
          withQueueItemId:[[QueueID alloc] initWithUrl:queueId.url andCount:queueId.count + 0]];

 in both the:

-(void) audioPlayer:(STKAudioPlayer*)audioPlayer
            didFinishBufferingSourceWithQueueItemId:(NSObject*)queueItemId

and the:

-(void) audioPlayer:(STKAudioPlayer*)audioPlayer didFinishPlayingQueueItemId:(NSObject*)queueItemId
         withReason:(STKAudioPlayerStopReason)stopReason
        andProgress:(double)progress
        andDuration:(double)duration {
}

and I've tried it with +1 and +0, and they either jump to another song on touch, meaning that I try to play song No. 4, and it starts playing song No. 5, or play and end too soon.

Can you tell from this what we are doing wrong?

Thanks!

**Comment by doriansgithub** [comment] 2017-05-10 16:00
So my question is really, how do we stop the player from playing the next song too soon.

**Comment by doriansgithub** [comment] 2017-05-10 16:49
Also, and this might be another ticket (issue), but when using gapless, there is still a very tiny, but still noticeable gap between the songs.

**Comment by doriansgithub** [comment] 2017-05-12 03:38
Found the issue with the player starting early.  Was feeding a wrong value to the progress.

**Comment by doriansgithub** [comment] 2017-05-16 23:19
Can't get it to work, even with your instructions.  We just can't find a way to have the player be a separate instance.   If a sample was provided on how to get EQ from a local URL, then we'd be able to use it.  It's a shame, so much work.

**Comment by iDevelopper** [comment] 2017-05-19 04:36
What do you mean by separate instance?

**Comment by doriansgithub** [comment] 2017-05-19 05:04
Well, we have the player, that just plays, but per Tums instructions, you have to create a new player to have the EQ, so we used the "Super" init instance to place the initWithOptions.  

I have a Metronome on my app, and if I don't comment out the entire (instancetype)init... it won't work.

We'll create a switch for that, that's probably easy, but basically with this code, every time we use the sliders, the sound dies.

Like this:

@implementation StreamingPlayer

(instancetype)init {
self = [super initWithOptions:(STKAudioPlayerOptions) {
.flushQueueOnSeek = YES,
.enableVolumeMixer = NO,
.readBufferSize = 0,
.bufferSizeInSeconds = 0,
.secondsRequiredToStartPlaying = 0,
.gracePeriodAfterSeekInSeconds = 0,
.secondsRequiredToStartPlayingAfterBufferUnderun = 0,
.equalizerBandFrequencies =
32.0, 42.0, 52.0, 64.0, 74.0,14000.0, 16000.0
}
}];
if (self) {
self.delegate = self;
}
return self;
}

**Comment by iDevelopper** [comment] 2017-05-19 10:36
Equalizer works well, see this sample:

[STKSample.zip](https://github.com/tumtumtum/StreamingKit/files/1013872/STKSample.zip)

**Comment by doriansgithub** [comment] 2017-05-20 15:23
Thanks for that sample, I had not seen and it looks very promising!  Thank you!

**Comment by doriansgithub** [comment] 2017-05-24 17:45
Hi, going back to the long files playing, it seems it is a StreamingKit issue going back to 2015.

https://github.com/tumtumtum/StreamingKit/issues/223

"file with more than 5.30 min failed with error STKAudioPlayerErrorStreamParseBytesFailed"

Any idea when this will be fixed, this is a critical issue, as users will be extremely frustrated not to be able to listen to many songs.

Thanks!

**Comment by iDevelopper** [comment] 2017-05-24 20:03
No problem here with that. #345 sample works.

**Comment by doriansgithub** [comment] 2017-05-24 20:55
Maybe because it's playing thru a desktop machine with greater capabilities?  Because yes, the sample works.

**Comment by patrickjquinn** [comment] 2017-05-25 08:34
Maybe its mentioned previously, but what device is this being tested on?

**Comment by iDevelopper** [comment] 2017-05-25 09:10
iPhone 6S and iPad mini 1

**Comment by doriansgithub** [comment] 2017-05-25 12:54
iPhone 6Plus.  I'll upload in a couple of hours.

**Comment by doriansgithub** [comment] 2017-05-25 16:25
Here is a link to one of them.  But we are talking about many.  This file is in Apple Lossless, which is how I import from CDs, but you need to downgrade it to 256 kbps, when synching, which is what I do.

https://www.sendspace.com/file/g38cmw

**Comment by iDevelopper** [comment] 2017-05-26 08:24
Converted to m4a Apple and it works:


[03 Lord of the Thighs (Live Version; 2012 Remaster) converted.m4a.zip](https://github.com/tumtumtum/StreamingKit/files/1031229/03.Lord.of.the.Thighs.Live.Version.2012.Remaster.converted.m4a.zip)

**Comment by doriansgithub** [comment] 2017-05-26 14:36
On the iPhone?

**Comment by doriansgithub** [comment] 2017-05-26 14:59
Can you show us how you have your streamingkit methods set up?  The 5 of them that queue the songs, etc?

Maybe the people that are having this issue are making the same mistake.

**Comment by doriansgithub** [comment] 2017-05-26 15:34
This is what I have:

#pragma mark
#pragma mark STKAudioPlayerDelegate

/// Raised when the state of the player has changed
-(void) audioPlayer:(STKAudioPlayer*)audioPlayer stateChanged:
            (STKAudioPlayerState)state previousState:(STKAudioPlayerState)previousState {
    NSLog(@"State = %ld", (long)state);
}

// Raised when an unexpected and possibly unrecoverable error has occured
// (usually best to recreate the STKAudioPlauyer)
-(void) audioPlayer:(STKAudioPlayer*)audioPlayer unexpectedError:
            (STKAudioPlayerErrorCode)errorCode {
    NSLog(@"Error = %ld", (long)errorCode);
}

/// Raised when an item has started playing
-(void) audioPlayer:(STKAudioPlayer*)audioPlayer didStartPlayingQueueItemId:(NSObject*)queueItemId {

    [_mediaDelegate updateNextSongInfo];
    NSLog(@"Started: %@", [QueueID description]);
}

/// Raised when an item has finished buffering (may or may not be the currently playing item)
/// This event may be raised multiple times for the same item if seek is invoked on the player
-(void) audioPlayer:(STKAudioPlayer*)audioPlayer didFinishBufferingSourceWithQueueItemId:(NSObject*)queueItemId {

    QueueID* queueId = (QueueID*)queueItemId;

    NSLog(@"didFinishBuffering: %@", [queueId.url description]);

    MPMediaItem *item =
    [MediaPlayerNavigation nextSongFromArray:UniversallyPlayer.defaultPlayer.arrSongs
                                     isQueue:YES];
    
    [MediaPlayerNavigation fillSongInfo:item];

    NSURL *url = [item valueForProperty:MPMediaItemPropertyAssetURL];

    NSLog(@"Requeuing: %@", [queueId.url description]);

    [self queueDataSource:[STKAudioPlayer dataSourceFromURL:url]
          withQueueItemId:[[QueueID alloc] initWithUrl:queueId.url andCount:queueId.count + 0]];
}

/// Raised when an item has finished playing
-(void) audioPlayer:(STKAudioPlayer*)audioPlayer didFinishPlayingQueueItemId:(NSObject*)queueItemId
         withReason:(STKAudioPlayerStopReason)stopReason
        andProgress:(double)progress
        andDuration:(double)duration {

    NSLog(@"Finished: %@", [QueueID description]);

}

-(void) audioPlayer:(STKAudioPlayer *)audioPlayer logInfo:(NSString *)line {
    NSLog(@"%@", line);
}

**Comment by iDevelopper** [comment] 2017-05-26 17:13
I said I converted your m4a via an appication: https://geranium-soft.com/products/audio-converter-lite/

After, I could play the converted file with StreamingKit

**Comment by doriansgithub** [comment] 2017-05-26 17:52
Downloaded it and I now get this message from iTunes.
[Screen Shot 2017-05-26 at 10.50.48 AM.zip](https://github.com/tumtumtum/StreamingKit/files/1032616/Screen.Shot.2017-05-26.at.10.50.48.AM.zip)

**Comment by doriansgithub** [comment] 2017-05-26 17:55
WTH?  Now I'm getting that message even for songs that haven't been converted!   Apple is INSANE!

**Comment by doriansgithub** [comment] 2017-05-26 18:10
Well, I think this entire thing is caused by going lossless and then to m4a.  I might have to re-encode my library.  I'll figure this out and close this issue when confirmed.

**Comment by doriansgithub** [comment] 2017-05-27 00:29
So I ripped the cd from scratch and synched at FULL resolution with no encoding, and NO issues.
So this is NOT a bug of StreamingKit, but something to do with the encoding.

Case closed!

iDevelopper wins the day!

**Closed** 2019-03-27 18:31 UTC
